USE MASTER
GO
IF EXISTS(SELECT NAME FROM SYSDATABASES WHERE NAME='QLLichHen')
	DROP DATABASE QLLichHen
GO
CREATE DATABASE QLLichHen
GO
USE QLLichHen
GO

CREATE TABLE KHACHHANG
(
MSKH CHAR(15)			NOT NULL PRIMARY KEY,
TENKH NVARCHAR(50)		NOT NULL,
CMT VARCHAR(10)			NOT NULL,
PHAI NCHAR(10)			NULL,
NGAYSINH DATETIME		NOT NULL,
DIACHI NVARCHAR(100)	NOT NULL,
DIENTHOAI VARCHAR(10)	NOT NULL
)	
GO
---
CREATE TABLE NHANVIEN
(
MANV CHAR(15)			NOT NULL PRIMARY KEY,
TENNV NVARCHAR(50)		NOT NULL,
DIENTHOAI NVARCHAR(10)	NOT NULL,
NGAYSINH DATETIME		NOT NULL,
PHAI NCHAR(10)			NOT NULL,
DIACHI NVARCHAR(100)	NOT NULL
)
GO
CREATE TABLE BACSI
(
MSBS CHAR(15)			NOT NULL PRIMARY KEY,
TENBS NVARCHAR(100)		NOT NULL,
DIENTHOAI NVARCHAR(10)	NOT NULL,
NGAYSINH DATETIME		NOT NULL,
PHAI NCHAR(10)			NOT NULL,
DIACHI NVARCHAR(100)	NOT NULL,
TRINHDO NVARCHAR(50)	NOT NULL,
KHOA NVARCHAR(50)		NOT NULL,
CHUCVU NVARCHAR(50)		NOT NULL

)
---
GO
---
CREATE TABLE PHIEUHEN
(
MSPH CHAR(15)	NOT NULL PRIMARY KEY,
MANV CHAR(15)	NOT NULL,
MSBS CHAR(15)	NOT NULL,
MSKH CHAR(15)	NOT NULL,
NGAYLPH DATETIME NOT NULL,
NOIDUNGKHAM NVARCHAR(100) NOT NULL,
NGAYHEN	DATETIME NOT NULL,
TG NVARCHAR(20) NOT NULL
-----------
	CONSTRAINT FK_PHIEUHEN1
	FOREIGN KEY (MANV)
	REFERENCES  NHANVIEN(MANV)
)
GO
---
------------KHOA NGOAI-------
ALTER TABLE PHIEUHEN
	ADD CONSTRAINT FK_PHIEUHEN2
	FOREIGN KEY (MSKH)
	REFERENCES KHACHHANG(MSKH);
----
GO
ALTER TABLE PHIEUHEN
	ADD CONSTRAINT FK_PHIEUHEN3
	FOREIGN KEY (MSBS)
	REFERENCES BACSI(MSBS);