USE QLLichHen
GO
---------------------------------------------KHÁCH HÀNG------------------------------------------
--1.Hàm tạo mã số khách hàng tự động

IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_TAOMSKH' )
	DROP PROCEDURE pr_TAOMSKH
GO
CREATE PROCEDURE pr_TAOMSKH
AS
BEGIN
	-- CHƯA CÓ NGƯỜI TIÊM
	IF NOT EXISTS(SELECT*FROM KHACHHANG)
		SELECT 'KH'+'0001'
	--ĐÃ CÓ NGƯỜI TIÊM
	ELSE
		BEGIN
		DECLARE @KH1 VARCHAR(15),
				@KH2 VARCHAR(15)
		SELECT @KH1 = MAX(MSKH)FROM KHACHHANG
		SET @KH2=RIGHT(RTRIM(@KH1),4)+1
		IF LEN(@KH2)=1
			SELECT 'KH'+'000'+@KH2
		ELSE IF LEN(@KH2)=2
				SELECT 'KH'+'00'+@KH2
			 ELSE IF LEN(@KH2)=3
					SELECT 'KH'+'0'+@KH2
				  ELSE IF LEN(@KH2)=4
					SELECT 'KH'+@KH2
		END
END
----2.viết PROCEDURE xem ds khach hang
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_DSKH')
	DROP PROCEDURE pr_DSKH
GO
CREATE PROCEDURE pr_DSKH
AS
BEGIN
SELECT*FROM KHACHHANG 
END
----3.viết PROCEDURE pr_THEMKH

GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_THEMKH' )
	DROP PROCEDURE pr_THEMKH
GO
CREATE PROCEDURE pr_THEMKH
(
@MSKH	CHAR(15),
@TENKH	NVARCHAR(50),
@CMT	VARCHAR(10),
@PHAI	NVARCHAR(5),
@NGAYSINH	DATETIME,
@DIACHI		NVARCHAR(100),
@DIENTHOAI	VARCHAR(10)
)
AS
SET DATEFORMAT DMY
BEGIN
	
	IF EXISTS(SELECT*FROM KHACHHANG WHERE MSKH = @MSKH OR CMT = @CMT)
		RAISERROR (N'Khách hàng [%s] đã tồn tại!',16,1,@TENKH)
	ELSE 
		BEGIN
			INSERT KHACHHANG(MSKH, TENKH, CMT, PHAI, NGAYSINH, DIACHI, DIENTHOAI)
			VALUES(@MSKH, @TENKH, @CMT, @PHAI, @NGAYSINH, @DIACHI, @DIENTHOAI)
			RAISERROR (N'Khách hàng [%s] đã được thêm vào danh sách thành công!',16,1,@TENKH)
		END
END

--SELECT*FROM KHACHHANG
 ---pr_THEMKH 'KH0007','Nguyễn Du',1236754987,'Nam','12/06/2001','Thủ Thừa Long An',0814547688
 /*
	----4.Procedure Tìm Khách hàng
*/
GO
 IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_TIMKH')
DROP PROCEDURE pr_TIMKH
GO
CREATE PROCEDURE pr_TIMKH
(
	@MSKH	CHAR(15),
	@TENKH	NVARCHAR(50),
	@CMT	VARCHAR(10),
	@DIACHI	NVARCHAR(100),
	@DIENTHOAI NVARCHAR(10)
)
AS
BEGIN
	IF @MSKH<>''
		SELECT*FROM KHACHHANG WHERE MSKH LIKE '%' + @MSKH +'%'
	ELSE
		IF @TENKH<>''
			SELECT*FROM KHACHHANG WHERE TENKH LIKE '%' + @TENKH +'%' 
		ELSE
			IF @CMT<>''
				SELECT*FROM KHACHHANG WHERE CMT LIKE '%' + @CMT +'%'
			ELSE
				IF @DIACHI<>''
					SELECT*FROM KHACHHANG WHERE DIACHI LIKE '%' + @DIACHI +'%'
				ELSE
					IF @DIENTHOAI<>''
							SELECT*FROM KHACHHANG WHERE DIENTHOAI LIKE '%' + @DIENTHOAI +'%'
END

----5.Hàm Xoá khách hàng
GO
 IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_XOAKH')
DROP PROCEDURE pr_XOAKH
GO
CREATE PROCEDURE pr_XOAKH
(
@MSKH	CHAR(15)
)
AS
BEGIN
	DELETE  FROM KHACHHANG
	WHERE MSKH= @MSKH
	RAISERROR (N'Bạn đã xoá Khách Hàng có mã số [%s]!',16,1,@MSKH)
END


--SELECT*FROM KHACHHANG
--EXEC pr_XOAKH 'KH0016'

---6.Sửa/cập nhật khách hàng
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_CAPNHATKH' )
	DROP PROCEDURE pr_CAPNHATKH
GO
CREATE PROCEDURE pr_CAPNHATKH
(
@MSKH	CHAR(15),
@TENKH	NVARCHAR(50),
@CMT	VARCHAR(10),
@PHAI	NVARCHAR(5),
@NGAYSINH	DATETIME,
@DIACHI		NVARCHAR(100),
@DIENTHOAI	VARCHAR(10)
)
AS
SET DATEFORMAT DMY
BEGIN
	
	IF NOT EXISTS(SELECT*FROM KHACHHANG WHERE MSKH = @MSKH)
		RAISERROR (N'Khách Hàng [%s] không tồn tại!',16,1,@TENKH)
	ELSE 
		BEGIN
			UPDATE KHACHHANG 
			SET		TENKH=@TENKH, CMT=@CMT, PHAI=@PHAI, NGAYSINH=@NGAYSINH, DIACHI=@DIACHI, DIENTHOAI=@DIENTHOAI
			WHERE MSKH = @MSKH;
			RAISERROR (N'Khách Hàng [%s] đã được cập nhật vào danh sách thành công!',16,1,@TENKH)
		END
END
--
--SELECT*FROM NHANVIEN
/*
MANV CHAR(15)			NOT NULL PRIMARY KEY,
TENNV NVARCHAR(50)		NOT NULL,
DIENTHOAI NVARCHAR(10)	NOT NULL,
NGAYSINH DATETIME		NOT NULL,
PHAI NCHAR(10)			NOT NULL,
DIACHI NVARCHAR(100)	NOT NULL
*/
------------------------------------------------------------------------------NHÂN VIÊN----------------------------------------------------------------
--1.Hàm tạo mã số nhân viên tự động
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_MANV' )
	DROP PROCEDURE pr_MANV
GO
CREATE PROCEDURE pr_MANV
AS
BEGIN
	-- CHƯA CÓ NGƯỜI TIÊM
	IF NOT EXISTS(SELECT*FROM NHANVIEN)
		SELECT 'NV'+'001'
	--ĐÃ CÓ NGƯỜI TIÊM
	ELSE
		BEGIN
		DECLARE @KH1 VARCHAR(15),
				@KH2 VARCHAR(15)
		SELECT @KH1 = MAX(MANV) FROM NHANVIEN
			SET @KH2=RIGHT(RTRIM(@KH1),3)+1
			IF LEN(@KH2)=1
				SELECT 'NV'+'00'+@KH2
			ELSE IF LEN(@KH2)=2
					SELECT 'NV'+'0'+@KH2
				ELSE IF LEN(@KH2)=3
						SELECT 'NV'+@KH2
		END
END
GO
----2.Thêm nhân viên

GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_THEMNV' )
	DROP PROCEDURE pr_THEMNV
GO
CREATE PROCEDURE pr_THEMNV
(
@MANV	CHAR(15),
@TENNV	NVARCHAR(50),
@PHAI	NVARCHAR(5),
@NGAYSINH	DATETIME,
@DIACHI		NVARCHAR(100),
@DIENTHOAI	VARCHAR(10)
)
AS
SET DATEFORMAT DMY
BEGIN
	
	IF EXISTS(SELECT*FROM NHANVIEN WHERE MANV = @MANV)
		RAISERROR (N'Nhân Viên [%s] đã tồn tại!',16,1,@TENNV)
	ELSE 
		BEGIN
			INSERT NHANVIEN(MANV, TENNV, PHAI, NGAYSINH, DIACHI, DIENTHOAI)
			VALUES(@MANV, @TENNV, @PHAI, @NGAYSINH, @DIACHI, @DIENTHOAI)
			RAISERROR (N'Nhân Viên [%s] đã được thêm vào danh sách thành công!',16,1,@TENNV)
		END
END
GO
--select*from NHANVIEN
---- 3. Tìm nhân viên
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_TIMNV')
DROP PROCEDURE pr_TIMNV
GO
CREATE PROCEDURE pr_TIMNV
(
	@TENNV	NVARCHAR(100)
)
AS
BEGIN

		IF @TENNV<>''
			SELECT*FROM NHANVIEN WHERE TENNV LIKE '%'+ @TENNV+'%'
		ELSE IF @TENNV=''
			SELECT*FROM NHANVIEN
END

GO
SELECT*FROM NHANVIEN
EXEC pr_TIMNV 'NV006'
----4.viết PROCEDURE xem ds nhân viên
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_DSNV')
	DROP PROCEDURE pr_DSNV
GO
CREATE PROCEDURE pr_DSNV
AS
BEGIN
SELECT*FROM NHANVIEN
END
GO

---exec pr_TIMNV N'NGUYỄN'
--exec pr_DSNV

--
----5.Hàm Xoá NHÂN VIÊN
GO
 IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_XOANV')
DROP PROCEDURE pr_XOANV
GO
CREATE PROCEDURE pr_XOANV
(
@MANV	CHAR(15)
)
AS
BEGIN
	DELETE  FROM NHANVIEN
	WHERE MANV= @MANV
	RAISERROR (N'Bạn đã xoá Nhân Viên có mã số [%s]!',16,1,@MANV)
END


--SELECT*FROM NHANVIEN
--EXEC pr_XOANV 'KH0016'

---6.Sửa/cập nhật khách hàng
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_CAPNHATNV' )
	DROP PROCEDURE pr_CAPNHATNV
GO
CREATE PROCEDURE pr_CAPNHATNV
(
@MANV	CHAR(15),
@TENNV	NVARCHAR(50),
@PHAI	NVARCHAR(5),
@NGAYSINH	DATETIME,
@DIACHI		NVARCHAR(100),
@DIENTHOAI	VARCHAR(10)
)
AS
SET DATEFORMAT DMY
BEGIN
	
	IF NOT EXISTS(SELECT*FROM NHANVIEN WHERE MANV = @MANV)
		RAISERROR (N'Nhân Viên [%s] không tồn tại!',16,1,@TENNV)
	ELSE 
		BEGIN
			UPDATE NHANVIEN 
			SET		MANV=@MANV,TENNV=@TENNV, PHAI=@PHAI, NGAYSINH=@NGAYSINH, DIACHI=@DIACHI, DIENTHOAI=@DIENTHOAI
			WHERE MANV=@MANV;
			RAISERROR (N'Nhân viên [%s] đã được cập nhật vào danh sách thành công!',16,1,@TENNV)
		END
END
---
----------------------------------------------------BÁC SĨ-----------------------------------------------------
GO
--1.Hàm tạo mã số bác sĩ tự động
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_MSBS' )
	DROP PROCEDURE pr_MSBS
GO
CREATE PROCEDURE pr_MSBS
AS
BEGIN
	-- CHƯA CÓ 
	IF NOT EXISTS(SELECT*FROM BACSI)
		SELECT 'BS'+'001'
	--ĐÃ CÓ 
	ELSE
		BEGIN
		DECLARE @BS1 VARCHAR(15),
				@BS2 VARCHAR(15)
		SELECT @BS1 = MAX(MSBS) FROM BACSI
			SET @BS2=RIGHT(RTRIM(@BS1),3)+1
			IF LEN(@BS2)=1
				SELECT 'BS'+'00'+@BS2
			ELSE IF LEN(@BS2)=2
					SELECT 'BS'+'0'+@BS2
				ELSE IF LEN(@BS2)=3
						SELECT 'BS'+@BS2
		END
END
GO
----2.Thêm nhân viên

GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_THEMBS' )
	DROP PROCEDURE pr_THEMBS
GO
CREATE PROCEDURE pr_THEMBS
(
@MSBS	CHAR(15),
@TENBS	NVARCHAR(50),
@PHAI	NVARCHAR(5),
@NGAYSINH	DATETIME,
@DIACHI		NVARCHAR(100),
@DIENTHOAI	VARCHAR(10),
@TRINHDO	NVARCHAR(50),
@KHOA	NVARCHAR(50),
@CHUCVU NVARCHAR(50)

)
AS
SET DATEFORMAT DMY
BEGIN
	
	IF EXISTS(SELECT*FROM BACSI WHERE MSBS = @MSBS)
		RAISERROR (N'Bác Sĩ [%s] đã tồn tại!',16,1,@TENBS)
	ELSE 
		BEGIN
			INSERT BACSI(MSBS, TENBS, PHAI, NGAYSINH, DIACHI, DIENTHOAI,TRINHDO,KHOA,CHUCVU)
			VALUES(@MSBS, @TENBS, @PHAI, @NGAYSINH, @DIACHI, @DIENTHOAI,@TRINHDO,@KHOA,@CHUCVU)
			RAISERROR (N'Bác sĩ [%s] đã được thêm vào danh sách thành công!',16,1,@TENBS)
		END
END
GO
--select*from NHANVIEN
---- 3. Tìm nhân viên
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_TIMBS')
DROP PROCEDURE pr_TIMBS
GO
CREATE PROCEDURE pr_TIMBS
(
	@TENBS	NVARCHAR(50)
)
AS
BEGIN

		IF @TENBS<>''
			SELECT*FROM BACSI WHERE TENBS LIKE '%' + @TENBS +'%'
		ELSE IF @TENBS=''
			SELECT*FROM BACSI
END

GO
----4.viết PROCEDURE xem ds nhân viên
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_DSBS')
	DROP PROCEDURE pr_DSBS
GO
CREATE PROCEDURE pr_DSBS
AS
BEGIN
SELECT * FROM BACSI
END
GO

--exec pr_TIMBS N'tr'
--exec pr_DSBS

--MSBS, TENBS, PHAI, NGAYSINH, DIACHI, DIENTHOAI,TRINHDO, KHOA , CHUCVU
----5.Hàm Xoá BÁC SĨ
GO
 IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_XOABS')
DROP PROCEDURE pr_XOABS
GO
CREATE PROCEDURE pr_XOABS
(
@MSBS	CHAR(15)
)
AS
BEGIN
	DELETE  FROM BACSI
	WHERE MSBS= @MSBS
	RAISERROR (N'Bạn đã xoá Bác Sĩ có mã số [%s]!',16,1,@MSBS)
END


--SELECT*FROM BÁC SĨ
--EXEC pr_XOABS 'KH0016'

---6.Sửa/cập nhật khách hàng
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_CAPNHATBS' )
	DROP PROCEDURE pr_CAPNHATBS
GO
CREATE PROCEDURE pr_CAPNHATBS
(
@MSBS	CHAR(15),
@TENBS	NVARCHAR(50),
@PHAI	NVARCHAR(5),
@NGAYSINH	DATETIME,
@DIACHI		NVARCHAR(100),
@DIENTHOAI	VARCHAR(10),
@TRINHDO	NVARCHAR(50),
@KHOA	NVARCHAR(50),
@CHUCVU NVARCHAR(50)
)
AS
SET DATEFORMAT DMY
BEGIN
	
	IF NOT EXISTS(SELECT*FROM BACSI WHERE MSBS = @MSBS)
		RAISERROR (N'Bác Sĩ [%s] không tồn tại!',16,1,@TENBS)
	ELSE 
		BEGIN
			UPDATE BACSI 
			SET		MSBS=@MSBS,TENBS=@TENBS, PHAI=@PHAI, NGAYSINH=@NGAYSINH, DIACHI=@DIACHI, DIENTHOAI=@DIENTHOAI, TRINHDO=@TRINHDO, KHOA=@KHOA, CHUCVU=@CHUCVU
			WHERE MSBS=@MSBS
			RAISERROR (N'Bác sĩ [%s] đã được cập nhật vào danh sách thành công!',16,1,@TENBS)
		END
END

--------------------------------------------------------- PHIẾU HIỆN -------------------------------------------------------------------------------------
---1.tìm PHIEU HEN
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_TIMPH')
	DROP PROCEDURE pr_TIMPH
GO
CREATE PROCEDURE pr_TIMPH
(
	@TENKH NVARCHAR(100),
	@NGAYHEN DATETIME
)
AS
BEGIN
	IF @TENKH <> ''
		BEGIN
			SELECT PH.MSPH , NV.TENNV, KH.TENKH, BS.TENBS, PH.NGAYLPH,PH.NOIDUNGKHAM,PH.NGAYHEN,PH.TG
			FROM PHIEUHEN PH, KHACHHANG KH, NHANVIEN NV, BACSI BS
			WHERE	PH.MSKH = KH.MSKH AND
					PH.MANV = NV.MANV AND
					PH.MSBS = BS.MSBS  AND
					KH.TENKH LIKE '%'+@TENKH+'%'
		END
	ELSE
		BEGIN
			SELECT PH.MSPH , NV.TENNV, KH.TENKH, BS.TENBS, PH.NGAYLPH,PH.NOIDUNGKHAM,PH.NGAYHEN,PH.TG
			FROM PHIEUHEN PH, KHACHHANG KH, NHANVIEN NV, BACSI BS
			WHERE	PH.MSKH = KH.MSKH AND
					PH.MANV = NV.MANV AND
					PH.MSBS =BS.MSBS  AND
					PH.NGAYHEN = @NGAYHEN
		END
END
GO
--EXEC pr_TIMPH 'PH',''

--SELECT*FROM PHIEUHEN
/*
2.Procedure Tạo Mã phiếu HEN tự động
*/
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_TAOMAPH')
DROP PROCEDURE pr_TAOMAPH
GO
CREATE PROCEDURE pr_TAOMAPH
AS
BEGIN
----.Xét chưa có
IF NOT EXISTS(SELECT*FROM PHIEUHEN)
	SELECT 'PH' + CAST(YEAR(GETDATE())AS VARCHAR)+
				  CAST(FORMAT(GETDATE(),'MM')AS VARCHAR)+
				  CAST(FORMAT(GETDATE(),'dd')AS VARCHAR)+'0001'
----.Đã có 
ELSE
	BEGIN
		DECLARE @PH1 VARCHAR(15),
				@PH2 VARCHAR(15)
		SELECT @PH1 = MAX(MSPH) FROM PHIEUHEN
		SET @PH2 = RIGHT(RTRIM(@PH1),4)+1
		IF LEN(@PH2)=1
				SELECT 'PH' + CAST(YEAR(GETDATE())AS VARCHAR)+
							  CAST(FORMAT(GETDATE(),'MM')AS VARCHAR)+
							  CAST(FORMAT(GETDATE(),'dd')AS VARCHAR)+'000'+@PH2
		ELSE
			IF LEN(@PH2)=2
					SELECT 'PH' + CAST(YEAR(GETDATE())AS VARCHAR)+
								  CAST(FORMAT(GETDATE(),'MM')AS VARCHAR)+
								  CAST(FORMAT(GETDATE(),'dd')AS VARCHAR)+'00'+@PH2
			ELSE
				IF LEN(@PH2)=3
					SELECT 'PH' + CAST(YEAR(GETDATE())AS VARCHAR)+
								  CAST(FORMAT(GETDATE(),'MM')AS VARCHAR)+
								  CAST(FORMAT(GETDATE(),'dd')AS VARCHAR)+'0'+@PH2
				ELSE
				SELECT 'PH' + CAST(YEAR(GETDATE())AS VARCHAR)+
								  CAST(FORMAT(GETDATE(),'MM')AS VARCHAR)+
								  CAST(FORMAT(GETDATE(),'dd')AS VARCHAR)+@PH2
	END
END
GO
----3 .Danh sach phiếu hẹn
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_DSPH')
	DROP PROCEDURE pr_DSPH
GO
CREATE PROCEDURE pr_DSPH
AS
BEGIN
SELECT PH.MSPH , NV.TENNV, KH.TENKH, BS.TENBS, PH.NGAYLPH,PH.NOIDUNGKHAM, PH.NGAYHEN,PH.TG
			FROM PHIEUHEN PH, KHACHHANG KH, NHANVIEN NV, BACSI BS
			WHERE	PH.MSKH = KH.MSKH AND
					PH.MANV = NV.MANV AND
					PH.MSBS =BS.MSBS
END
---
--4.thêm Phieu HEN
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_THEMPH' )
	DROP PROCEDURE pr_THEMPH
GO
CREATE PROCEDURE pr_THEMPH
(
@MSPH	CHAR(15),
@MANV	CHAR(15),
@MSBS	CHAR(15),
@MSKH	CHAR(15),
@NGAYLPH	DATETIME,
@NOIDUNGKHAM NVARCHAR(100),
@NGAYHEN	DATETIME ,
@TG NVARCHAR(20)
)
AS
SET DATEFORMAT DMY
BEGIN
		DECLARE
			@KT1 int =(SELECT COUNT(*) FROM PHIEUHEN WHERE 	MSBS = @MSBS AND NGAYHEN=@NGAYHEN AND TG=@TG)
		IF EXISTS(SELECT*FROM PHIEUHEN WHERE MSPH = @MSPH)
		RAISERROR (N'Mã Phiếu tiêm [%s] đã tồn tại!',16,1,@MSPH)
		ELSE	
			IF(@KT1>3)
				RAISERROR (N'Số người khám trong thời gian này đã Full!',16,1)
						ELSE	IF(@KT1<=3)								
									BEGIN
										INSERT PHIEUHEN(MSPH ,MANV, MSBS,MSKH,NGAYLPH,NOIDUNGKHAM,NGAYHEN,TG)
										VALUES(@MSPH, @MANV, @MSBS, @MSKH, @NGAYLPH, @NOIDUNGKHAM,@NGAYHEN,@TG)
										RAISERROR (N'Thêm Phiếu hẹn [%s]  thành công!',16,1,@MSPH)				
									END
END
GO
--EXEC pr_THEMPH 'PH0010', 'NV002', 'BS001','KH0001' ,'21/11/2022',N'Hẹn khám sức khoẻ','21/12/2022','7h - 9h'

----5.Hàm Xoá PHIẾU HẸN
GO
 IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_XOAPH')
DROP PROCEDURE pr_XOAPH
GO
CREATE PROCEDURE pr_XOAPH
(
@MSPH	CHAR(15)
)
AS
BEGIN
	DELETE  FROM PHIEUHEN
	WHERE MSPH=@MSPH
	RAISERROR (N'Bạn đã xoá Phiếu Hẹn có mã số [%s]!',16,1,@MSPH)
END

--SELECT*FROM PHIEUHEN
--EXEC pr_XOAPH 'KH0016'

---6.Sửa/cập nhật PHIEU HEN
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_CAPNHATPH' )
	DROP PROCEDURE pr_CAPNHATPH
GO
CREATE PROCEDURE pr_CAPNHATPH
(
@MSPH	CHAR(15),
@MANV	CHAR(15),
@MSBS	CHAR(15),
@MSKH	CHAR(15),
@NGAYLPH	DATETIME,
@NOIDUNGKHAM NVARCHAR(100),
@NGAYHEN	DATETIME ,
@TG NVARCHAR(20)
)
AS
SET DATEFORMAT DMY
BEGIN
	DECLARE
		@KT1 INT=(SELECT COUNT(*) FROM PHIEUHEN WHERE MSBS= @MSBS AND	NGAYHEN=@NGAYHEN AND TG=@TG)
	IF NOT EXISTS(SELECT*FROM PHIEUHEN WHERE MSPH = @MSPH)
		RAISERROR (N'Phiếu hẹn [%s] không tồn tại!',16,1,@MSPH)
	ELSE IF(@KT1>3)
			RAISERROR (N'Số người khám trong thời gian này đã Full!',16,1)
		ELSE IF(@KT1<=3)
		BEGIN				
			UPDATE PHIEUHEN 
			SET		MSPH=@MSPH, MANV=@MANV, MSBS=@MSBS, MSKH=@MSKH, NGAYLPH=@NGAYLPH, NOIDUNGKHAM=@NOIDUNGKHAM, NGAYHEN=@NGAYHEN, TG=@TG
			WHERE MSPH=@MSPH;
			RAISERROR (N'Phiếu Hẹn [%s] đã được cập nhật thành công!',16,1,@MSPH)
		END
END
---
--SELECT *FROM BACSI
--7.In Phiếu tiêm
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_INPH' )
	DROP PROCEDURE pr_INPH
GO
CREATE PROCEDURE pr_INPH
(
@MSPH	CHAR(15)
)
AS
BEGIN
SELECT	NV.MANV , NV.TENNV, NV.DIACHI AS DIACHINV,NV.DIENTHOAI AS DIENTHOAINV,
		KH.MSKH,KH.TENKH,KH.CMT,KH.NGAYSINH,KH.PHAI ,KH.DIACHI AS DIACHIKH,KH.DIENTHOAI AS DIENTHOAIKH,
		PH.MSPH,PH.NGAYLPH,NOIDUNGKHAM,NGAYHEN,TG,
		BS.MSBS,BS.TENBS
FROM KHACHHANG KH , NHANVIEN NV, PHIEUHEN PH, BACSI BS
WHERE	PH.MANV=NV.MANV AND
		PH.MSKH=KH.MSKH AND
		PH.MSBS=BS.MSBS AND
		PH.MSPH=@MSPH
END
GO
--SELECT*FROM PHIEUHEN 
--EXEC pr_INPH 'PH0001'
----8 lịch hen trong ngày
GO
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_LHTN' )
	DROP PROCEDURE pr_LHTN
GO
CREATE PROCEDURE pr_LHTN

AS
SET DATEFORMAT DMY
BEGIN
SELECT	NV.MANV , NV.TENNV, NV.DIACHI AS DIACHINV,NV.DIENTHOAI AS DIENTHOAINV,
		KH.MSKH,KH.TENKH,KH.CMT,KH.NGAYSINH,KH.PHAI ,KH.DIACHI AS DIACHIKH,KH.DIENTHOAI AS DIENTHOAIKH,
		PH.MSPH,PH.NGAYLPH,NOIDUNGKHAM,NGAYHEN,TG,
		BS.MSBS,BS.TENBS
FROM KHACHHANG KH , NHANVIEN NV, PHIEUHEN PH, BACSI BS
WHERE	PH.MANV=NV.MANV AND
		PH.MSKH=KH.MSKH AND
		PH.MSBS=BS.MSBS AND
		PH.NGAYHEN = '21/12/2022'
END
GO
--EXEC pr_LHTN

-----------------------------------------------------------BACKUP-RESTORE-----------------------------
--1. Viết stored procedue BACKUP DATABASE
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_BACKUPDATA')
	DROP  PROC pr_BACKUPDATA

GO
CREATE PROC pr_BACKUPDATA
(
@TEN_DATABASE	NVARCHAR(30),
@TEN_TAPTIN		NVARCHAR(200)
)
AS
BEGIN
IF @TEN_DATABASE<>''
   IF @TEN_TAPTIN<>''
	   BEGIN
			BACKUP DATABASE @TEN_DATABASE TO DISK=@TEN_TAPTIN
			RAISERROR(N'Backup Database thành công!!!',16,1)
		END
	ELSE
		RAISERROR(N'Tên tập tin không được đẻ trống!!!',16,1)
ELSE
	RAISERROR(N'Tên Database không được đẻ trống!!!',16,1)
END
--
GO
/* Gọi stored procedue BACKUP DATABASE
USE QLTiemBACSI
GO 
EXEC pr_BACKUPDATA @TEN_DATABASE='QLTiemBACSI',@TEN_TAPTIN='D:\BT\CNPM\My Projects\Database\qlTBS.bak'
GO
*/
USE MASTER
GO
--2. Viết stored procedue RESTORE DỮ LIỆU 

IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='pr_RESTORE')
	DROP  PROC pr_RESTORE
GO
CREATE PROC pr_RESTORE
(
@TEN_DATABASE	NVARCHAR(30),
@TEN_TAPTIN		NVARCHAR(200)
)
AS
BEGIN
IF @TEN_DATABASE<>''
   IF @TEN_TAPTIN<>''
	   BEGIN
			RESTORE DATABASE @TEN_DATABASE FROM DISK = @TEN_TAPTIN
			RAISERROR(N'Restore Database thành công!!!',16,1)
		END
	ELSE
		RAISERROR(N'Tên tập tin không được đẻ trống!!!',16,1)
ELSE
	RAISERROR(N'Tên Database không được đẻ trống!!!',16,1)
END
GO

/*USE MASTER
GO 
IF EXISTS(SELECT NAME FROM SYSDATABASES WHERE NAME= 'QLTiemBACSI')
	DROP DATABASE QLTiemBACSI
GO
EXEC pr_RESTORE @TEN_DATABASE='QLLichHen',@TEN_TAPTIN='C:\Users\Admin\Desktop\New folder\aa.bak'
*/
GO
USE QLLichHen
